# Generated by Django 3.1.7 on 2021-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hacker',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
